#!/bin/bash
function extrimg(){
    dname=$(dirname "$1")
    filename=$(basename "$1")
    extension="${filename##*.}"
    filename="${filename%.*}"
    echo "$dname"
    od="$dname"/$(echo $filename | tr ' ' '_')_images;
    echo "$od"
    echo "$filename"
    if [[ ($extension == 'docx') || ($extension == 'doc') ]]; then
        echo word
        unzip  "$1" 'word/media/*' -d $od;
        mv $od/word/media/* $od;
        rm -rf $od/word;       
    fi
    
    if [ $extension == 'odt' ]; then
        echo odt
        unzip  "$1" 'Pictures/*' -d "$od";
        mv $od/Pictures/* $od;
        rm -rf $od/Pictures/
    fi

    if [ $extension == 'pdf' ]; then
        mkdir $od
        pdfimages -j "$1" $od/img
    fi
}

extrimg "$1"
